SELECT  ROUTE, 
        CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE,
        CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC
/*CONCAT 쓰면 TOTAL_DISTANCE가 문자열이 됨!!*/
/*반올림(ROUND) 조심!!!!!*/